/**
 * Single source of truth for the site's canonical origin and public URL
 * inventory. Everything that emits an absolute URL reads from here:
 *
 *   - src/components/SEO/SEO.jsx        (canonical, hreflang, OG, JSON-LD)
 *   - index.html                         (via the SEO assets Vite plugin)
 *   - sitemap.xml, robots.txt            (generated by the same plugin)
 *   - _redirects                         (generated by the same plugin)
 *
 * To move the site to a different domain, change SITE_URL below and nothing
 * else. If you are also retiring an older domain, set PREVIOUS_SITE_URL and
 * then HOST_REDIRECTS_CONFIRMED — see docs/DOMAIN-MIGRATION.md.
 *
 * This module must stay free of React, browser APIs and Node built-ins: it is
 * imported from both the browser bundle and vite.config.js.
 *
 * It must also not import from ./seo.js, even for constants. seo.js reads
 * SITE_URL from here at module-evaluation time to build DEFAULT_OG_IMAGE, so
 * an import in the other direction would make that read hit an uninitialised
 * binding. Keep the dependency one-way: site.js is the base layer.
 */

/** Canonical origin. No trailing slash, no path. Always https. */
export const SITE_URL = 'https://dentalcarebest.in';

/** Brand name used in <title>, og:site_name, schema `name` and file names. */
export const SITE_NAME = 'Incapremo Dental Care';

/**
 * An older canonical origin being retired, without a trailing slash.
 *
 * This is `null` because the site has never run on another domain —
 * dentalcarebest.in is the first. It is kept as a documented hook for a future
 * move: setting it blocks the build until HOST_REDIRECTS_CONFIRMED is true,
 * because a domain change without a zone-level 301 silently loses ranking.
 *
 * Note that Workers Static Assets ignores domain-level redirects in
 * `_redirects`, so a future migration needs a Cloudflare Bulk Redirect on the
 * retired domain. See docs/DOMAIN-MIGRATION.md.
 */
export const PREVIOUS_SITE_URL = null;

/**
 * Acknowledgement flag: set to true only after the zone-level redirect for
 * PREVIOUS_SITE_URL (and any CANONICAL_ALIASES) is live in the Cloudflare
 * dashboard and verified with `curl -I`.
 *
 * The build fails while this is false, because a domain migration without a 301
 * silently loses the ranking signal it was meant to keep — and nothing in the
 * build output would otherwise reveal that.
 */
export const HOST_REDIRECTS_CONFIRMED = false;

/** Alternate origin that should 301 to SITE_URL, e.g. the `www` variant. */
export const CANONICAL_ALIASES = [];

/** Bumped whenever on-page content changes, to keep sitemap lastmod honest. */
export const LAST_MODIFIED = '2026-09-26';

/** Open Graph / Twitter card image, relative to SITE_URL. */
export const OG_IMAGE = 'oie_Xo2NfYNrbzXd.png';

/**
 * Every indexable route. Order here is the priority order.
 *
 * `path` must match the route in src/App.jsx and the `url` prop passed to
 * <SEO>, because SEO.jsx normalises both the same way and asserts on it.
 * Paths are written without a trailing slash to match the canonical URLs
 * emitted by toAbsolute().
 */
export const INDEXABLE_ROUTES = [
  {
    path: '/',
    changefreq: 'weekly',
    priority: '1.0',
    images: [],
  },
  {
    path: '/services',
    changefreq: 'monthly',
    priority: '0.9',
    images: [],
  },
  {
    path: '/emergency',
    changefreq: 'monthly',
    priority: '0.9',
    images: [],
  },
  {
    path: '/about',
    changefreq: 'monthly',
    priority: '0.8',
    images: [],
  },
  {
    path: '/contact',
    changefreq: 'monthly',
    priority: '0.8',
    images: [],
  },
  {
    path: '/proof-of-work',
    changefreq: 'weekly',
    priority: '0.7',
    images: [
      { src: 'gall1.webp', title: 'Restored smile after dental treatment' },
      { src: 'gall2.webp', title: 'Pediatric dental care in progress' },
      { src: 'gall3.webp', title: 'Preventive dental treatment result' },
      { src: 'gall4.jpeg', title: 'Modern dental clinical setup' },
      { src: 'gall5.jpeg', title: 'Advanced dental equipment and tools' },
      { src: 'gall6.jpeg', title: 'Happy patient after dental procedure' },
    ],
  },
];

/** Routes that must never be indexed, and so are kept out of the sitemap. */
export const DISALLOWED_PATHS = ['/404', '/500'];

/**
 * Real pages that must not be indexed, so they are absent from the sitemap but
 * still get a prerendered HTML file carrying `noindex, follow`. They need their
 * own file: without one they fall through to the 404 handler and report a false
 * missing-page status for a page that genuinely exists.
 *
 * NOINDEX_PATHS is derived from PAGE_SEO's `noindex` flag in src/config/seo.js,
 * which owns the title and description. It is intentionally not re-exported
 * here — see the note on the one-way dependency above.
 */

/** Join SITE_URL and a route path into an absolute URL, no double slashes. */
export function absoluteUrl(path = '/') {
  if (/^https?:\/\//i.test(path)) return path;
  const suffix = path.startsWith('/') ? path : `/${path}`;
  return `${SITE_URL}${suffix === '/' ? '/' : suffix.replace(/\/+$/, '')}`;
}

/** Turn a sitemap `src` into an absolute URL for an <image:loc> entry. */
export function absoluteAssetUrl(src) {
  return absoluteUrl(src.startsWith('/') ? src : `/${src}`);
}
